import { SUBJECTS } from '../data/subjects.js';
const KEY='shotdeck26';let cache=null;
const read=()=>{if(cache)return cache;try{cache=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{cache={};}cache.watched=cache.watched||{};cache.chapterOpen=cache.chapterOpen||{};return cache;};
const write=()=>{try{localStorage.setItem(KEY,JSON.stringify(read()));}catch{}};
export const getWatched=k=>read().watched[k]||[];
export const isWatched=(k,n)=>getWatched(k).includes(Number(n));
export const toggleWatched=(k,n)=>{const w=getWatched(k);const i=w.indexOf(Number(n));if(i>=0)w.splice(i,1);else w.push(Number(n));read().watched[k]=w;write();return w.includes(Number(n));};
export const watchedCount=k=>getWatched(k).length;
export const subjectPct=s=>(!s||!s.chapters||!s.chapters.length)?0:Math.round(watchedCount(s.key)/s.chapters.length*100);
export const overallProgress=()=>{let t=0,d=0;SUBJECTS.forEach(s=>{if(s.chapters){t+=s.chapters.length;d+=watchedCount(s.key);}});return{total:t,done:d,pct:t?Math.round(d/t*100):0};};
export const isChapterOpen=k=>!!read().chapterOpen[k];
export const setChapterOpen=(k,v)=>{read().chapterOpen[k]=!!v;write();};
export const getVolume=()=>typeof read().volume==='number'?read().volume:100;
export const setVolume=v=>{read().volume=v;write();};
export const getSpeed=()=>typeof read().speed==='number'?read().speed:1;
export const setSpeed=s=>{read().speed=s;write();};
export const getCollapsed=()=>!!read().collapsed;
export const setCollapsed=c=>{read().collapsed=!!c;write();};
export const getTheme=()=>document.documentElement.getAttribute('data-theme')||'dark';
export const setTheme=t=>{if(t!=='dark'&&t!=='light')t='dark';document.documentElement.setAttribute('data-theme',t);try{localStorage.setItem('shotdeck:theme',t);}catch{}};
export const toggleTheme=()=>setTheme(getTheme()==='dark'?'light':'dark');
export const toggleIcon=()=>{const I={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',moon:'<path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${getTheme()==='dark'?I.sun:I.moon}</svg>`;};
export const rgba=(h,a)=>{const n=parseInt(h.replace('#',''),16);return`rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`;};
export const setAccent=c=>{const s=document.documentElement.style;s.setProperty('--accent',c);['06','10','14','22','40'].forEach(p=>s.setProperty('--accent-'+p,rgba(c,parseInt(p)/100)));};
